dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.0"
dotenv: .env
wallets:
  from_key: ${ROPSTEN_PRIVATE_KEY}
